###  GetPepole by id
GET  http://localhost:4567/hfswapi/getPeople/3?format=wookiee

### Geet planet  by id
GET  http://localhost:4567/hfswapi/getPlanet/2

### Get weight on planet random
GET  http://localhost:4567/hfswapi/getWeightOnPlanetRandom/


### Get logs
GET  http://localhost:4567/hfswapi/getLogs